@host = http://localhost:5059

### Criar proposta
POST {{host}}/api/propostas
Content-Type: application/json

{
  "cpfCliente": "12345678901",
  "valorSolicitado": 15000,
  "quantidadeParcelas": 24
}

### Listar propostas
GET {{host}}/api/propostas

### Consultar proposta (troque pelo id devolvido na criação)
GET {{host}}/api/propostas/00000000-0000-0000-0000-000000000000

### Aprovar (true) ou recusar (false) uma proposta em análise
PUT {{host}}/api/propostas/00000000-0000-0000-0000-000000000000/status
Content-Type: application/json

{
  "aprovado": true
}
